mybatis:
  typeAliasesPackage: com.tom.domain
  mapperLocations:  classpath:mappers/*.xml
#
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gs-spring-boot-mybatis-freemarker
    username: root
    password:
    initialize: true
    schema: schema.sql
    data: data.sql

logging:
    level:
        org.springframework: INFO
        com.example: DEBUG